"""Hatchling build hook: make ``pip install -e .`` work with the ``src`` -> ``book_translator`` rename.

Hatchling refuses its automatic dev-mode when a ``sources`` rewrite changes a
prefix (it can only strip one).  With ``dev-mode-dirs`` set, hatchling instead
writes a plain ``.pth`` and honours ``force_include_editable``; this hook uses
that to install a tiny meta-path finder that maps the top-level name
``book_translator`` to ``<project>/src``.  Regular (non-editable) wheels are
untouched: the ``sources`` mapping in ``pyproject.toml`` handles them.
"""

from __future__ import annotations

import os
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

_FINDER_MODULE = "_book_translator_editable"

_FINDER_TEMPLATE = '''"""Editable-install shim generated by hatch_build.py: maps book_translator -> src."""
import importlib.util
import sys

_SRC_DIR = {src_dir!r}
_SRC_INIT = {src_init!r}


class _BookTranslatorFinder:
    @classmethod
    def find_spec(cls, fullname, path=None, target=None):
        if fullname != "book_translator":
            return None
        return importlib.util.spec_from_file_location(
            fullname, _SRC_INIT, submodule_search_locations=[_SRC_DIR]
        )


if not any(getattr(f, "__name__", "") == _BookTranslatorFinder.__name__ for f in sys.meta_path):
    sys.meta_path.append(_BookTranslatorFinder)
'''


class EditableFinderHook(BuildHookInterface):  # type: ignore[misc]
    PLUGIN_NAME = "custom"

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        if version != "editable":
            return
        src_dir = os.path.join(self.root, "src")
        gen_dir = os.path.join(self.root, ".hatch-editable")
        os.makedirs(gen_dir, exist_ok=True)

        finder_path = os.path.join(gen_dir, f"{_FINDER_MODULE}.py")
        with open(finder_path, "w", encoding="utf-8") as fh:
            fh.write(
                _FINDER_TEMPLATE.format(
                    src_dir=src_dir, src_init=os.path.join(src_dir, "__init__.py")
                )
            )
        pth_path = os.path.join(gen_dir, f"{_FINDER_MODULE}.pth")
        with open(pth_path, "w", encoding="utf-8") as fh:
            fh.write(f"import {_FINDER_MODULE}\n")

        forced = build_data.setdefault("force_include_editable", {})
        forced[finder_path] = f"{_FINDER_MODULE}.py"
        forced[pth_path] = f"{_FINDER_MODULE}.pth"
